### ISSUE TITLE
Propose yalphabetize to open source projects

### ISSUE THREAD

**Issue by samrjenkins** [samrjenkins/yalphabetize#71]
Rubocop
Devise
Rspec
Rails

**Comment by tagliala** [comment]
Hi,

I'm tracking the progresses of the gem and how the community is reacting, so I've collected all the PRs and following discussions, I hope the following list may help

- [ ] Activeadmin: activeadmin/activeadmin#7333
- [ ] Diaspora: diaspora/diaspora#8338
- [ ] Rails I18n: svenfuchs/rails-i18n#982
- [ ] Open Street Map: openstreetmap/openstreetmap-website#3459
